include:
  - board: nice_nano//zmk
    shield: cheapinov2 raw_hid_adapter # <-- required for Raw HID support
    snippet: studio-rpc-usb-uart # <-- required for ZMK Studio support
# there is no settingsreset (needed) for the XIAO
